### ISSUE TITLE
Deploy theme as GitHub Pages

### ISSUE THREAD

**Issue by piyanatk** [stackbit-themes/ampersand-nextjs#5]
Hi,

I used the Stackbit page builder to convert this theme to Jekyll and was able to run the theme locally following the instructions in the Readme file. I would like to deploy the theme as a GitHub Pages site. I followed the [instruction from GitHub](https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll), commenting out `gem "jekyll", "~> 3.8.4"` and adding `gem "github-pages", "~> 206", group: :jekyll_plugins` into the `Gemfile`. Upon executing `bundle exec jekyll serve`, I got an error ``Liquid Exception: undefined method `map' for "/posts":String Did you mean? tap in /_layouts/home.html``. The full traceback is below.
```
Configuration file: /Users/piyanat/src/ampersand-jekyll-1a03c/_config.yml
            Source: /Users/piyanat/src/ampersand-jekyll-1a03c
       Destination: /Users/piyanat/src/ampersand-jekyll-1a03c/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Disabled in site.config.
  Liquid Exception: undefined method `map' for "/posts":String Did you mean? tap in /_layouts/home.html
jekyll 3.8.7 | Error:  undefined method `map' for "/posts":String
Did you mean?  tap
Traceback (most recent call last):
	60: from /Users/piyanat/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
	59: from /Users/piyanat/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
	58: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	57: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	56: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	55: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
	54: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	53: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
	52: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	51: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	50: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	49: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
	48: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
	47: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
	46: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
	45: from /Users/piyanat/.rbenv/versions/2.7.1/bin/jekyll:23:in `<top (required)>'
	44: from /Users/piyanat/.rbenv/versions/2.7.1/bin/jekyll:23:in `load'
	43: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/exe/jekyll:15:in `<top (required)>'
	42: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	41: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	40: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	39: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	38: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	37: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	36: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `start'
	35: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `each'
	34: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `block in start'
	33: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:36:in `process'
	32: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:65:in `build'
	31: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/command.rb:28:in `process_site'
	30: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:71:in `process'
	29: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:192:in `render'
	28: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:471:in `render_pages'
	27: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:471:in `each'
	26: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:472:in `block in render_pages'
	25: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:479:in `render_regenerated'
	24: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:62:in `run'
	23: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:88:in `render_document'
	22: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	21: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:195:in `render_layout'
	20: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:126:in `render_liquid'
	19: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	18: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	17: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	16: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	15: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	14: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	13: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	12: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	11: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	10: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
	 9: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	 8: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:26:in `render'
	 7: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
	 6: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
	 5: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
	 4: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
	 3: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
	 2: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
	 1: from /Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/filters.rb:243:in `sort'
/Users/piyanat/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jekyll-3.8.7/lib/jekyll/filters.rb:303:in `sort_input': undefined method `map' for "/posts":String (NoMethodError)
Did you mean?  tap
```

**Comment by smnh** [comment]
Hi @piyanatk,

Unfortunately, Stackbit themes does not yet officially support GitHub pages. GitHub pages have very limited support for Jekyll sites and their gem dependencies. You should check that the your Jekyll site does not use anything that is not supported by [GitHub pages dependency version](https://pages.github.com/versions/).

What I can say for sure, is that when Stackbit generates Jekyll sites, it adds at least one dependency that is not supported by GitHub pages, and it is the `jekyll-menus` plugins. There might be other Jekyll features not supported by GitHub pages. Check out the docs at [About GitHub Pages and Jekyll](https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll).
Specifically this line:
> GitHub Pages cannot build sites using unsupported plugins. If you want to use unsupported plugins, generate your site locally and then push your site's static files to GitHub.

From the logs you have pasted above I can see that there is some `map` filter used inside `/_layouts/home.html`. I wasn't able to find it when creating a fresh Jekyll site from an Ampersand theme. So I assume this one was added later. Check if there is something new added to the home layout that might cause it.
